//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ReceiptManagement.Common.Helpers.Exceptions
{
    /// <summary>
    ///	The exception thrown when an error occurs when a user authentication failed.
    /// </summary>
    [System.Serializable]
    public sealed class NotAuthenticatedException : System.Exception
    {
    	#region Constructors & Factories
    
        //	Internal constructors since they shouldn't be called outside of the API.
        internal NotAuthenticatedException() { }
    	internal NotAuthenticatedException(System.Exception innerException) : base(innerException.Message, innerException) { }
        internal NotAuthenticatedException(System.String message):base(message) { }
    		
    	/// <summary>
    	///		The factory used to a new NotAuthenticatedException with inner exception.
    	/// </summary>
        public static Helpers.Exceptions.NotAuthenticatedException Factory(System.Exception innerException)
    	{		
            return new Helpers.Exceptions.NotAuthenticatedException(innerException);
        }
    	
    	/// <summary>
    	///		The factory used to a new NotAuthenticatedException with a message.
    	/// </summary>
        public static Helpers.Exceptions.NotAuthenticatedException Factory(System.String message)
    	{
            return new Helpers.Exceptions.NotAuthenticatedException(message);
        }
    		
    	#endregion
    }
}
